#!/usr/bin/with-contenv sh

usage(){
	echo "SECRET=... environment variable MUST be set"
}

if [ -z "$SECRET" ]; then
	usage
	rm /etc/nginx/nginx.conf
	exit 1
fi

if [ -z "$SECRET_KEY" ]; then
	SECRET_KEY=`pwgen -s 64 1`
fi
if [ -z "$DATABASE_URL" ]; then
	DATABASE_URL="sqlite:///data/db.sqlite"
fi
if [ -z "$ALLOWED_HOST" ]; then
	ALLOWED_HOST="localhost"
fi
if [ -z "$BEANSTALK" ]; then
	BEANSTALK="127.0.0.1"
fi
if [ -z "$BEANSTALK_PORT" ]; then
	BEANSTALK_PORT=11300
fi
if [ "$REGISTER_ALLOWED" != "false" ]; then
	REGISTER_ALLOWED=True
else
	REGISTER_ALLOWED=False
fi

cat << EOF > /grader/grader/local_settings.py
import dj_database_url

DEBUG = False
DATABASES['default'] = dj_database_url.parse(default="$DATABASE_URL")
SECRET_KEY = "$SECRET_KEY"
ALLOWED_HOSTS = ["$ALLOWED_HOST"]
WORKER_SHARED_SECRET = "$SECRET"
BEANSTALK = ("$BEANSTALK", $BEANSTALK_PORT)
REGISTER_ALLOWED = $REGISTER_ALLOWED
STATIC_URL = '/'
STATIC_ROOT = '/var/www/localhost/htdocs/'
MEDIA_ROOT = '/data/media/'
EOF
