#!/usr/bin/with-contenv bash

usage(){
	echo "SECRET=... environment variable MUST be set"
}

if [ -z "$SECRET" ]; then
	usage
	rm /etc/nginx/nginx.conf
	exit 1
fi

SECRET_KEY=${SECRET_KEY:-`pwgen -s 64 1`}
DATABASE_URL=${DATABASE_URL:-sqlite:////data/db.sqlite}
BEANSTALK=${BEANSTALK:-127.0.0.1}
BEANSTALK_PORT=${BEANSTALK_PORT:-11300}
if [ -z "$ALLOWED_HOST" ]; then
	ALLOWED_HOST="localhost"
	DEBUG=True
else
	DEBUG=False
fi
if [ "$REGISTER_ALLOWED" != "false" ]; then
	REGISTER_ALLOWED=True
else
	REGISTER_ALLOWED=False
fi

cat << EOF > /grader/grader/local_settings.py
import dj_database_url

DEBUG = $DEBUG
DATABASES = {'default': dj_database_url.parse("$DATABASE_URL")}
DATABASES['default']['CONN_MAX_AGE'] = 600
SECRET_KEY = "$SECRET_KEY"
ALLOWED_HOSTS = ["$ALLOWED_HOST", "web"]
WORKER_SHARED_SECRET = "$SECRET"
BEANSTALK = ("$BEANSTALK", $BEANSTALK_PORT)
REGISTER_ALLOWED = $REGISTER_ALLOWED
STATIC_URL = '/'
STATIC_ROOT = '/var/www/htdocs/'
MEDIA_ROOT = '/data/media/'
EOF
