# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0002_auto_20160611_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Created'), (1, 'Grading'), (2, 'Graded')], default=0)),
                ('correct', models.IntegerField(blank=True, choices=[(None, 'Not graded'), (0, 'Incorrect'), (1, 'Correct'), (2, 'Error')], null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('code', models.TextField()),
                ('lang', models.CharField(max_length=10)),
                ('error', models.TextField(blank=True, default=None, null=True)),
                ('count_stats', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='result',
            index_together=set([('user', 'state', 'correct', 'problem'), ('id', 'state', 'correct', 'count_stats')]),
        ),
    ]
