# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('point', models.IntegerField(default=1)),
                ('creator', models.CharField(blank=True, default='', max_length=255)),
                ('graders', models.TextField(blank=True)),
                ('input_lang', models.CharField(blank=True, choices=[('py', 'Python 2'), ('java', 'Java'), ('php', 'PHP')], max_length=10, null=True, verbose_name='Input generator language')),
                ('input', models.FileField(null=True, upload_to='input', verbose_name='Input generator source')),
                ('output_lang', models.CharField(blank=True, choices=[('c', 'C'), ('cpp', 'C++'), ('cs', 'C#'), ('java', 'Java'), ('js', 'JavaScript'), ('php', 'PHP'), ('py', 'Python'), ('py3', 'Python 3'), ('rb', 'Ruby')], max_length=10, null=True, verbose_name='Solution language')),
                ('output', models.FileField(null=True, upload_to='output', verbose_name='Solution')),
                ('comparator', models.CharField(choices=[('hash', 'Grader')], default='hash', editable=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('practice', 'Practice')], default='practice', editable=False, max_length=15)),
                ('start', models.DateTimeField(help_text='Time to start this test. Users without permission will not see the test until this time', null=True)),
                ('end', models.DateTimeField(help_text='Time to end this test. Users without permission will be unable to submit solution', null=True)),
                ('readonly', models.BooleanField(default=False, help_text='Disable submission. Users with permission will still able to submit solution regardless.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Test'),
        ),
    ]
