# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input',
            field=models.FileField(blank=True, null=True, upload_to='input', verbose_name='Input generator source'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output',
            field=models.FileField(blank=True, null=True, upload_to='output', verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='test',
            name='end',
            field=models.DateTimeField(blank=True, help_text='Time to end this test. Users without permission will be unable to submit solution', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='start',
            field=models.DateTimeField(blank=True, help_text='Time to start this test. Users without permission will not see the test until this time', null=True),
        ),
    ]
