# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 13:11
from __future__ import unicode_literals
import json
import yaml

from django.db import migrations

def convert_yaml(apps, schema_editor):
    Problem = apps.get_model('problems', 'Problem')

    for problem in Problem.objects.all():
        try:
            data = json.loads(problem.graders)
            data = data['grader']
        except (ValueError, KeyError, TypeError):
            data = {}
        problem.graders = yaml.dump(data, default_flow_style=False)
        problem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20160611_2337'),
    ]

    operations = [
        migrations.RunPython(convert_yaml)
    ]
