# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-id']},
        ),
    ]
