# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import problems.models
import problems.storage
import problems.validators


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20160615_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['test', 'name']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='problem',
            name='creator',
            field=models.CharField(blank=True, default='', help_text='Any text is OK', max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, help_text='<a href="http://commonmark.org/help/">Markdown</a> and full HTML allowed'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='graders',
            field=models.TextField(blank=True, default='time_limit: 1\nmemory_limit: 64\nallowed:\n- java', help_text='Allowed are list of file extensions, not language name. Must be valid YAML', validators=[problems.validators.validate_grader_schema], verbose_name='Grader configuration'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input',
            field=models.FileField(blank=True, null=True, storage=problems.storage.CodeloadFileSystemStorage('input'), upload_to=problems.models.input_filename, verbose_name='Input generator source'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_lang',
            field=models.CharField(blank=True, choices=[('py', 'Python 2'), ('py3', 'Python 3')], max_length=10, null=True, verbose_name='Input generator language'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output',
            field=models.FileField(blank=True, null=True, storage=problems.storage.CodeloadFileSystemStorage('output'), upload_to=problems.models.output_filename, verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_lang',
            field=models.CharField(blank=True, choices=[('java', 'Java'), ('py', 'Python'), ('py3', 'Python 3')], max_length=10, null=True, verbose_name='Solution language'),
        ),
    ]
